### ISSUE TITLE
ドキュメントクラスオプションの包括的な説明

### ISSUE THREAD

**Issue by liqsuq** [reviewml/reviewknowledge-ja#1]
まずre:view3.2を利用していますが、
Latexに関しては見識が浅い事をお断りしておきます。

原稿の再利用を簡単にするために、書籍作成の前に普段作成する
簡素なドキュメントをre:viewで作成出来ないかと考えていました。

その際にはやはり表紙や奥付、奇数ページの改ページは不要ですので、
sty以下に手を加える必要があるかと思っていました。
しかしjsbook.clsを見てみると既にドキュメントクラスオプションとして
"report"が定義されており、思惑が叶いそうな事が確認出来ました。

このオプションはナレッジベース、pdfmaker.md及びsty/README.mdに説明がありません。
後続のために、本来の用途と異なりますがどこかで紹介していただきたく思います。
願わくば未言及の他のオプションについても説明があればと思います。

**Comment by kmuto** [comment]
コメントありがとうございます。

実のところ私自身はjsbookクラスを使っていない(通常は業務用のクラスか、jlreq.cls)ので、jsbook固有のオプションについてはあまり深い知見がありません。
reportオプションはjsbookに最近めで追加されたもののようですね。

openanyなどの代表的なものはdocかknowledgeに載せつつ、あとはjsclassesの紹介ページにリンクという方向で考えます。

**Comment by kmuto** [comment]
Re:VIEWのreview-jsbook/README.mdにつっこむことにしました(review-style.styのfancyhdrが今となっては負債ですね…)。

https://github.com/kmuto/review/pull/1365

**Comment by liqsuq** [comment]
Latex使っていた頃fancyhdrは愛用していたので自分には馴染みがあって助かるのですが、re:viewから入る人からすれば弄る/覚える物が余計にあって億劫でしょうね…

ともあれ、ドキュメントに載る方針になったため、reviewmlとしてのこのissueはクローズします。
ご対応ありがとうございました。
