### ISSUE TITLE
unicode_display_width → unicode-display_width

### ISSUE THREAD

**Issue by liqsuq** [reviewml/reviewknowledge-ja#2]
開発チームのみコミットとのことでしたのでひとまずこちらで失礼します。

docs/latex/linebreak-verbatim.mdの一文、
"Unicode での文字の幅の判定のために unicode_display_width という gem を使っているので…"ですが、
少なくともUbuntu18.04、ruby2.5.1ではunicode-display_widthでした。

インストール失敗時にサジェストされるのでさして困らないですが一応。

**Comment by kmuto** [comment]
おぉ、ありがとうございます、修正しました 51724db
