### ISSUE TITLE
使用書体の変更（upLaTeX 編）の更新

### ISSUE THREAD

**Issue by takahashim** [reviewml/reviewknowledge-ja#6]
「[使用書体の変更（upLaTeX 編）](https://review-knowledge-ja.readthedocs.io/ja/latest/latex/uptex-fonts.html)」ですが、現代はharanoajiフォントを推奨するのが良さそうに思いました。

**Comment by kmuto** [comment]
ありがとうございます、追加しておきました。Docker vvakame/reviewだとデフォルトで原の味ですね(TeXLiveのjapaneseデフォルトでもそうなってたかも)。
